CREATE TABLE FORUM  (
id INT NOT NULL PRIMARY KEY IDENTITY,
title NVARCHAR(255) NOT NULL,
posttext NVARCHAR(255) NOT NULL,
posttype NVARCHAR(255) NOT NULL );


INSERT INTO FORUM (title, posttext, posttype) VALUES ('TEST', 'TEST','TEST');